name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: RenPy Build
        uses: ProjectAliceDev/renpy-build-action@v1.3.0
        with:
          sdk-version: '8.1.1'
          project-dir: '.'
          package: 'android'
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hell-yeah-build
          path: '**/*.apk'
